[licensing]: Database design and middleware for PGP validation
BladimirOrihuela-Hexaware/Talos-Help pull request #23
Opened 2023-04-26 00:50 UTC by BenjaminGuzman-Hexaware

2023-04-27 18:25 UTC, BladimirOrihuela-Hexaware requested changes

2023-04-27 19:27 UTC, BenjaminGuzman-Hexaware commented on backend/licensing/package.json
> +        "@nestjs/cli": "^9.0.0",
IMO nest cli should be a dev dependency because its sole purpose is to help initializing, developing and maintaining the application and that is useless in a production container (that's why `start:prod` npm script is `node dist/main` rather than `nest start` which corresponds to `start` script).

Since skaffold is used for local deployment too, I'd suggest having two kinds of images:
1. The production-ready and optimized minimal image of the microservice (meant to be uploaded to docker hub). This image would use commands like `npm install --only=prod` and `node main.js`
2. The development image of the microservice (meant to be built and kept locally only). This image would use commands like `npm install` and `npm start:dev`.

Or, even not using containers at all and use something like [microstart](https://github.com/BenjaminGuzman/microstart) (only for development I mean).

2023-04-28 00:20 UTC, BladimirOrihuela-Hexaware commented on backend/licensing/package.json
> +        "@nestjs/cli": "^9.0.0",
I like the idea. You're right, we don't have to tie the development with a docker image.

2023-04-28 00:21 UTC, BladimirOrihuela-Hexaware approved these changes

2023-04-28 22:13 UTC, EderQuintana-Hexaware approved these changes

2023-04-28 23:27 UTC, DanielaCuevas-Hexaware approved these changes

2023-05-02 20:51 UTC, BladimirOrihuela-Hexaware approved these changes

2023-05-02 20:51 UTC, merged