✨[Actions] : Created actions service
BladimirOrihuela-Hexaware/Talos-Help pull request #26
Opened 2023-04-26 15:21 UTC by EduardoCastillo-Hexaware

## Description
Created actions service adding as first action the "accept" one;

URL : http://localhost:3000/actions/latest/docs#/actions

2023-04-26 17:58 UTC, BladimirOrihuela-Hexaware requested changes

2023-04-26 17:58 UTC, BladimirOrihuela-Hexaware commented on backend/actions/src/app.controller.ts
> +    getIntegrations(): ActionsResponse {
getIntegrations() doesn't sound like a good function name. Please update it to something more accurate.

2023-04-26 17:58 UTC, BladimirOrihuela-Hexaware commented on backend/actions/src/app.controller.ts
> +    getIntegration(@Param("id") id: string): ActionResponse {
getIntegration doesn't sound like a good function name. Please update it to something more accurate.

2023-04-26 17:58 UTC, BladimirOrihuela-Hexaware commented on backend/actions/src/dto/actionsDto.dto.ts
> +    integrations: ActionBase[];
Also here, **integrations** doesn't seems to be a good name for returning an array of Actions.

2023-04-26 17:58 UTC, BladimirOrihuela-Hexaware commented on backend/actions/src/models/actions.ts
> +export type Actions2 = Action;
Please rename this type. Actions2 doesn't tell any useful information to the fellow developer that will read this. I suggest **ActionType** as the name of the type

2023-04-26 22:58 UTC, BenjaminGuzman-Hexaware requested changes

2023-04-26 22:58 UTC, BenjaminGuzman-Hexaware commented on backend/actions/src/models/actions.entity.ts
> +    panelTop:{ panelType: string; desc: string};
It'd be great if these properties had some documentation.
Is `panelType` some kind of enum or its values are restricted in some way?
What does `panelTop` means?

**Note**: If properties `panelTop` and `panelBottom` are named that way because it is intended that their information is seen in a panel at the top and a panel at the bottom, respectively, then please rename it since that implies a strict coupling with frontend layout.

2023-04-26 22:58 UTC, BenjaminGuzman-Hexaware commented on backend/actions/src/app.controller.ts
> +    @ApiResponse({
OpenAPI cannot identify schema for return type (ie. you should see no schema for the response in the OpenAPI docs).
That is very likely to be because `schema` property is missing in object passed to decorator.

2023-04-26 22:58 UTC, BenjaminGuzman-Hexaware commented on backend/actions/src/app.controller.ts
> +export class ActionController {
Ideally, there should be 1 controller per file

2023-04-26 22:58 UTC, BenjaminGuzman-Hexaware commented on backend/actions/src/app.controller.ts
> +        schema: { $ref: getSchemaPath(ActionsDto) },
Schema for response is identified as `{actions: []}` by OpenAPI.
This is very likely because `actions` prop value is an array of interface (should be array of class).

2023-04-26 22:58 UTC, BenjaminGuzman-Hexaware commented on backend/actions/src/app.controller.ts
> +export class ActionsController {
Ideally, file should be named after the controller (or vice versa), e.g. `app.controller.ts - AppController`, `actions.controller.ts - ActionsController`

2023-04-26 22:58 UTC, BenjaminGuzman-Hexaware commented on backend/actions/src/app.controller.spec.ts
> +            controllers: [ActionsController],
Testing `ActionController` but `ActionsController` is the only one registered (typo).

2023-04-26 22:58 UTC, BenjaminGuzman-Hexaware commented on backend/actions/src/app.controller.spec.ts
> +        expect(Actions[0]).toMatchObject({ ActionName: "Alert Accept", description: "Clicks on the 'OK' button as soon as any pop up window / alert appears.",
Test fails

2023-04-26 22:58 UTC, BenjaminGuzman-Hexaware commented on backend/actions/src/app.controller.spec.ts
> +        expect(Actions[0]).toMatchObject({ ActionName: "Alert Accept", description: "Clicks on the 'OK' button as soon as any pop up window / alert appears.",
`'ActionName' !== 'actionName'`

2023-04-26 23:45 UTC, BladimirOrihuela-Hexaware commented on backend/actions/src/app.controller.spec.ts
Please update the name of some tests in this file. Currently they're referencing a different service.

2023-04-28 01:47 UTC, EduardoCastillo-Hexaware commented on backend/actions/src/models/actions.entity.ts
> +    panelTop:{ panelType: string; desc: string};
- anum values are pending to applied for messageType
- PanelTop and PanelBottom were renamed

2023-04-28 01:49 UTC, EduardoCastillo-Hexaware commented on backend/actions/src/app.controller.ts
> +    @ApiResponse({
schema were not being correclty applied for actioncontroler, so we send  an actionResoponse instead to show an achema of the class in OpenAPI

2023-04-28 01:50 UTC, EduardoCastillo-Hexaware commented on backend/actions/src/app.controller.ts
> +export class ActionController {
Created a another file for the other controller class, now we have 2 controllers files instead of only one.

2023-04-28 01:51 UTC, EduardoCastillo-Hexaware commented on backend/actions/src/app.controller.ts
> +        schema: { $ref: getSchemaPath(ActionsDto) },
-The interfaces were changed to classes to avoid this issue

2023-04-28 01:52 UTC, EduardoCastillo-Hexaware commented on backend/actions/src/app.controller.ts
> +export class ActionsController {
The actions files were renamed, now we have 
   - actions.controller.ts
   - actions.modules.ts
   - actions.service.ts
   - etc..

2023-04-28 01:53 UTC, EduardoCastillo-Hexaware commented on backend/actions/src/app.controller.spec.ts
> +        expect(Actions[0]).toMatchObject({ ActionName: "Alert Accept", description: "Clicks on the 'OK' button as soon as any pop up window / alert appears.",
Test were updated, and now they are working as expected and unitTest were successfully Ran.

![image](https://user-images.githubusercontent.com/101907588/235035449-76060fb7-de25-46a7-98fc-f3b2e0cf2456.png)

2023-04-28 01:53 UTC, EduardoCastillo-Hexaware commented on backend/actions/src/app.controller.spec.ts
Test descriptions were changes to the corresponding service.

2023-04-28 17:03 UTC, BladimirOrihuela-Hexaware approved these changes

2023-04-28 19:25 UTC, BenjaminGuzman-Hexaware approved these changes

2023-04-28 19:26 UTC, EduardoCastillo-Hexaware commented on backend/actions/src/app.controller.spec.ts
> +            controllers: [ActionsController],
Changes Requested were applied.

2023-04-28 20:27 UTC, merged